server:
  port: 8080
spring:
  elasticsearch:
    uris: http://localhost:9200
  application:
    name: marketplace-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

  # Activation des tâches planifiées
  task:
    scheduling:
      enabled: true

jwt:
  secret: 5468576D5A7134743777217A25432A462D4A614E645267556B58703272357538
  expiration: 86400000

stripe:
  api:
    key: your_stripe_secret_key
  webhook:
    secret: your_stripe_webhook_secret

paypal:
  mode: sandbox
  client:
    id: your_paypal_client_id
    secret: your_paypal_client_secret

file:
  upload-dir: ./uploads

logging:
  level:
    root: INFO
    com.marketplace: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

# Configuration de springdoc pour Spring Boot 3.2.3
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
    configUrl: /api/v3/api-docs/swagger-config
    url: /api/v3/api-docs
  pathsToMatch: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized