server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: marketplace-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB

  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

jwt:
  secret: 5468576D5A7134743777217A25432A462D4A614E645267556B58703272357538
  expiration: 86400000

stripe:
  api:
    key: your_stripe_secret_key
  webhook:
    secret: your_stripe_webhook_secret

paypal:
  mode: sandbox
  client:
    id: your_paypal_client_id
    secret: your_paypal_client_secret

file:
  upload-dir: ./uploads

logging:
  level:
    root: INFO
    com.marketplace: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized